CensorReloaded:
  setup:
    prefix: "&5CENSOR-RELOADED &3> &c"
    lang: "en_US"
    bstats: true
  node_check_cmd:
    - /msg
    - /pm
    - /tell
    - /r
    - /w
  node_module:
    pmCheck: true
    spam: true
    adw: true
    bad: true
    ip: true
  filters:
    capssens: 15
    adw_rgx:
      - '\b(\w{1,9}):\/\/|(www\.)?([a-zA-Z9!@#$%^&*(),.?])+(\W|\d|_|\s)*(\.(\w{2,3}))'
    ip_rgx: '^(.* + \W|\d|_|.*)?\d{1,3}(\W|\d|\_|.*|)(\#|\.|\,\_\-\ \ \W|\d|\_|.*|)\d{1,3}(\W|\d|\_|.*|)(\#|\.|\,\_\-\ \ \W|\d|\_|.*|)\d{1,3}(\W|\d|\_|.*|)(\#|\.|\,\_\-\ \ \W|\d|\_|.*|)\d{1,3}(\W|\d\_|.*)?$'
