CensorReloaded:
  setup:
    prefix: "&8(&6CENSOR-RELOADED&8) &7> &e"
    lang: "en_US"
    bstats: true
  node_check_cmd: [/msg, /pm, /tell, /r, /w]
  node_website_whitelist:
    - www.example.com
    - https://www.example.com
    - http://www.exmaple.com
  node_module:
    checkPrivateCommands: true
    checkSpam: true
    checkSwear: true
    checkIPAddress: true
    checkWebSites: true
  filters:
    caps_sensitive: 15
    websites_rgx: '^(.* + \w{1,9}):\/\/|(www\.)?([a-zA-Z9!@#$%^&*(),.?])+(\W|\d|_|\s)*(\d|\W(\w{2,3}))(.*)$'
    ip_address_rgx: '^(.* + \W|\d|_|.*)?\d{1,3}(\W|\d|\_|.*|)(\#|\.|\,\_\-\ \ \W|\d|\_|.*|)\d{1,3}(\W|\d|\_|.*|)(\#|\.|\,\_\-\ \ \W|\d|\_|.*|)\d{1,3}(\W|\d|\_|.*|)(\#|\.|\,\_\-\ \ \W|\d|\_|.*|)\d{1,3}(\W|\d\_|.*)?$'